import { useState, useEffect } from 'react';
import { supabase } from '../lib/supabase';

export const useMoodboard = () => {
  const [savedOutfits, setSavedOutfits] = useState([]);

  // Fetch initial outfits from Supabase
  useEffect(() => {
    const fetchOutfits = async () => {
      const { data, error } = await supabase
        .from('user_outfits')
        .select('*')
        .order('created_at', { ascending: false });

      if (!error && data) {
        setSavedOutfits(data);
      } else {
        console.error('Failed to fetch outfits from Supabase:', error);
      }
    };
    fetchOutfits();
  }, []);

  const saveOutfit = async (outfit) => {
    try {
      let finalImageUrl = outfit.imageUrl;
      // If the image is a data URL (screenshot), upload it to Supabase Storage
      if (outfit.imageUrl && outfit.imageUrl.startsWith('data:image')) {
        const base64Data = outfit.imageUrl.split(',')[1];
        const byteCharacters = atob(base64Data);
        const byteNumbers = new Array(byteCharacters.length);
        for (let i = 0; i < byteCharacters.length; i++) {
          byteNumbers[i] = byteCharacters.charCodeAt(i);
        }
        const byteArray = new Uint8Array(byteNumbers);
        const file = new Blob([byteArray], { type: 'image/jpeg' });

        const fileName = `outfit_${Date.now()}.jpg`;
        const { data: uploadData, error: uploadError } = await supabase.storage
          .from('garments')
          .upload(`outfits/${fileName}`, file, { contentType: 'image/jpeg' });

        if (!uploadError) {
          const { data: { publicUrl } } = supabase.storage
            .from('garments')
            .getPublicUrl(`outfits/${fileName}`);
          finalImageUrl = publicUrl;
        } else {
          console.error("Failed to upload screenshot:", uploadError);
        }
      }

      // Convert local outfit format to Supabase table row
      const dbRecord = {
        name: outfit.name,
        garment_type: outfit.garmentType,
        color: outfit.color,
        image_url: finalImageUrl,
        measurements: outfit.measurements
        // id is generated by Supabase, created_at as well
      };

      const { data, error } = await supabase
        .from('user_outfits')
        .insert([dbRecord])
        .select();

      if (error) {
        console.error("Supabase insert error:", error);
        setSavedOutfits((prev) => [...prev, { ...outfit, imageUrl: finalImageUrl }]);
      } else if (data && data.length > 0) {
        // Use the db record to maintain the state
        const savedRecord = {
          id: data[0].id,
          name: data[0].name,
          date: new Date(data[0].created_at).toLocaleDateString(),
          measurements: data[0].measurements,
          garmentType: data[0].garment_type,
          color: data[0].color,
          imageUrl: data[0].image_url
        };
        setSavedOutfits((prev) => [...prev, savedRecord]);
      }
    } catch (err) {
      console.error("Error saving outfit:", err);
      setSavedOutfits((prev) => [...prev, outfit]);
    }
  };

  const removeOutfit = async (id) => {
    setSavedOutfits((prev) => prev.filter(o => o.id !== id));
    try {
      await supabase.from('user_outfits').delete().eq('id', id);
    } catch (err) {
      console.error("Failed to delete from Supabase:", err);
    }
  };

  return {
    savedOutfits,
    saveOutfit,
    removeOutfit
  };
};
